import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'ঐতিহ্যবাহী', image: 'https://picsum.photos/400/400?random=1', productCount: 142 },
  { id: '2', name: 'ইলেকট্রনিক্স', image: 'https://picsum.photos/400/400?random=2', productCount: 89 },
  { id: '3', name: 'ফ্যাশন', image: 'https://picsum.photos/400/400?random=3', productCount: 256 },
  { id: '4', name: 'ঘর সাজানো', image: 'https://picsum.photos/400/400?random=4', productCount: 67 },
  { id: '5', name: 'মিষ্টি ও খাবার', image: 'https://picsum.photos/400/400?random=5', productCount: 34 },
];

export const BRANDS = [
  { name: 'আড়ং', logo: 'https://picsum.photos/100/100?random=10' },
  { name: 'ওয়ালটন', logo: 'https://picsum.photos/100/100?random=11' },
  { name: 'প্রাণ', logo: 'https://picsum.photos/100/100?random=12' },
  { name: 'এপেক্স', logo: 'https://picsum.photos/100/100?random=13' },
  { name: 'ইয়েলো', logo: 'https://picsum.photos/100/100?random=14' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'প্রিমিয়াম জামদানি শাড়ি',
    tagline: 'বাংলার ঐতিহ্যের ছোঁয়া',
    description: 'বাংলার ঐতিহ্যবাহী হাতে বোনা জামদানি শাড়ি। দক্ষ কারিগরদের তৈরি এই শাড়িতে রয়েছে নিখুঁত জ্যামিতিক নকশা যা আপনাকে দেবে আভিজাত্যের ছোঁয়া।',
    price: 12500,
    oldPrice: 15000,
    rating: 4.8,
    reviews: 124,
    category: 'ঐতিহ্যবাহী',
    brand: 'আড়ং',
    image: 'https://picsum.photos/600/800?random=20',
    images: ['https://picsum.photos/600/800?random=20', 'https://picsum.photos/600/800?random=21'],
    sizes: ['ফ্রি সাইজ'],
    colors: ['লাল', 'সাদা', 'সোনালি'],
    isNew: true,
    stock: 15
  },
  {
    id: 'p2',
    title: 'ওয়ালটন প্রিমো ZX4',
    tagline: 'ফ্ল্যাগশিপ পারফরম্যান্স, দেশীয় গর্ব',
    description: 'ওয়ালটনের সর্বশেষ ফ্ল্যাগশিপ ফোন। ১২০ হার্টজ অ্যামোলেড ডিসপ্লে, স্ন্যাপড্রাগন প্রসেসর এবং ১০৮ মেগাপিক্সেল ক্যামেরা।',
    price: 32990,
    rating: 4.5,
    reviews: 89,
    category: 'ইলেকট্রনিক্স',
    brand: 'ওয়ালটন',
    image: 'https://picsum.photos/600/800?random=30',
    images: ['https://picsum.photos/600/800?random=30', 'https://picsum.photos/600/800?random=31'],
    sizes: ['১২৮ জিবি', '২৫৬ জিবি'],
    colors: ['মিডনাইট ব্ল্যাক', 'ওশান ব্লু'],
    isNew: true,
    stock: 50
  },
  {
    id: 'p3',
    title: 'ডিজাইনার পাঞ্জাবি',
    tagline: 'ঈদ কালেকশন ২০২৪',
    description: 'মার্জিত সুতি পাঞ্জাবি যাতে রয়েছে কলার এবং বুকে নিখুঁত এমব্রয়ডারি। উৎসব এবং বিয়ের জন্য উপযুক্ত।',
    price: 4500,
    oldPrice: 5200,
    rating: 4.7,
    reviews: 210,
    category: 'ফ্যাশন',
    brand: 'ইয়েলো',
    image: 'https://picsum.photos/600/800?random=40',
    images: ['https://picsum.photos/600/800?random=40'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['সাদা', 'নেভি'],
    stock: 30
  },
  {
    id: 'p4',
    title: 'বগুড়ার দই',
    tagline: 'বাংলার বিখ্যাত মিষ্টি',
    description: 'আসল বগুড়ার মিষ্টি দই, একেবারে তাজা। প্রতিটি বাঙালি পরিবারের পছন্দের ডেজার্ট।',
    price: 450,
    rating: 4.9,
    reviews: 500,
    category: 'মিষ্টি ও খাবার',
    brand: 'প্রাণ',
    image: 'https://picsum.photos/600/800?random=50',
    images: ['https://picsum.photos/600/800?random=50'],
    stock: 100
  },
  {
    id: 'p5',
    title: 'চামড়ার লোফার',
    tagline: 'আরাম এবং স্টাইল একসাথে',
    description: 'অফিস বা ক্যাজুয়াল আউটিংয়ের জন্য জেনুইন লেদার লোফার। টেকসই সোল এবং নরম ইনসোল।',
    price: 3200,
    rating: 4.4,
    reviews: 45,
    category: 'ফ্যাশন',
    brand: 'এপেক্স',
    image: 'https://picsum.photos/600/800?random=60',
    images: ['https://picsum.photos/600/800?random=60'],
    sizes: ['৩৯', '৪০', '৪১', '৪২'],
    colors: ['বাদামী', 'কালো'],
    stock: 20
  },
  {
    id: 'p6',
    title: 'নকশি কাঁথা',
    tagline: 'হাতের কাজের অনন্য নিদর্শন',
    description: 'বাংলাদেশের লোকশিল্পের প্রতিনিধিত্বকারী ঐতিহ্যবাহী নকশি কাঁথা।',
    price: 8500,
    rating: 4.9,
    reviews: 67,
    category: 'ঘর সাজানো',
    brand: 'আড়ং',
    image: 'https://picsum.photos/600/800?random=70',
    images: ['https://picsum.photos/600/800?random=70'],
    stock: 5
  },
  {
    id: 'p7',
    title: 'গেমিং হেডসেট',
    tagline: 'ইমারসিভ সাউন্ড এক্সপেরিয়েন্স',
    description: 'আরজিবি লাইট এবং নয়েজ ক্যান্সেলেশন সহ ওয়ালটন গেমিং হেডসেট।',
    price: 2100,
    rating: 4.2,
    reviews: 34,
    category: 'ইলেকট্রনিক্স',
    brand: 'ওয়ালটন',
    image: 'https://picsum.photos/600/800?random=80',
    images: ['https://picsum.photos/600/800?random=80'],
    stock: 45
  },
  {
    id: 'p8',
    title: 'ম্যাঙ্গো জুস বক্স',
    tagline: 'রাজশাহীর স্বাদ',
    description: 'রাজশাহীর ফজলি আম থেকে তৈরি ১২ টি তাজা ম্যাঙ্গো জুস বক্সের প্যাক।',
    price: 600,
    rating: 4.6,
    reviews: 890,
    category: 'মিষ্টি ও খাবার',
    brand: 'প্রাণ',
    image: 'https://picsum.photos/600/800?random=90',
    images: ['https://picsum.photos/600/800?random=90'],
    stock: 200
  }
];